---

language: python
python: "2.7"
sudo: required
dist: trusty

services:
  - mysql

# Install ansible
addons:
  apt:
    packages:
    - python-setuptools

before_install:
  - mysql -e 'CREATE DATABASE jabberd2;'

  - mysql jabberd2 < schema.sql

install:
  - sudo -H easy_install pip
  # http://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
  - sudo -H pip install -U pyOpenSSL cryptography idna certifi
  - sudo -H pip install -U urllib3
  # https://github.com/ansible/ansible/issues/23642#issuecomment-297469043
  - sudo -H pip install -U ndg-httpsclient

  # Install ansible
  - sudo -H pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - /usr/local/bin/jabberd2-router -h || true

  - sudo /etc/init.d/jabberd status

  - sudo netstat -lnp

  - sudo ps auxww | grep -i jabber

  - cat /var/log/jabberd2/*.log

  - curl -sSfi localhost:5222

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
