---

- name: create jabber user
  user:
    name: jabber
    home: /var/jabber
    system: yes
  become: yes

- name: create run folder
  file:
    path: /run/jabberd2
    state: directory
    mode: 0755
    owner: jabber
  become: yes

- stat:
    path: /etc/tmpfiles.d
  register: stat_tmpfilesd

- name: perma run folder
  copy:
    src: tmpfiles.conf
    dest: /etc/tmpfiles.d/jabberd2.conf
    mode: 0644
  become: yes
  when: stat_tmpfilesd.stat.exists

- name: create log folder
  file:
    path: /var/log/jabberd2
    state: directory
    mode: 0755
    owner: jabber
  become: yes

- name: add logrotate config
  copy:
    src: logrotate
    dest: /etc/logrotate.d/jabberd2
    mode: 0644
  become: yes

- name: apply configs
  template:
    src: "{{ item }}"
    dest: /etc/jabberd2/{{ item }}
    mode: 0644
  with_items:
    - c2s.xml
    - jabberd.cfg
    - router-filter.xml
    - router-users.xml
    - router.xml
    - s2s.xml
    - sm.xml
  become: yes
  notify: restart_jabberd2
