---

- name: install dependencies
  include_tasks: deps/{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml

- name: get current jabberd2 version
  command: /usr/local/bin/jabberd2-router -h
  register: jabberd2_current
  ignore_errors: yes

- include_tasks: compile-jabberd2.yml
  when: jabberd2_current.stdout is undefined or not jabberd2_current.stdout | search(jabberd2_version_string_match)

- include_tasks: config.yml

#- include_tasks: mu-conference.yml
