---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - make
    - gcc
    - pkg-config
    - ca-certificates
    - libudns-dev
    - libexpat1-dev
    - libidn11-dev
    - zlib1g-dev
    - libgsasl7-dev
    #- libhttp-parser-dev (needed for websockets only))
    - libssl-dev
    - default-libmysqlclient-dev
    - libglib2.0-dev
  become: yes
