---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - make
    - gcc
    - pkg-config
    - ca-certificates
    - libudns-dev
    - libexpat1-dev
    - libidn11-dev
    - zlib1g-dev
    - libgsasl7-dev
    #- libhttp-parser-dev (needed for websockets only))
    - libssl-dev
    - libmysqlclient-dev
    - libglib2.0-dev
  become: yes

- name: add systemd service
  copy:
    src: jabberd-muc.service.ini
    dest: /lib/systemd/system/jabberd-muc.service
    mode: 0644
  become: yes
  notify:
    - reload_systemd
    - restart_jabberd2

- name: enable muc
  service:
    name: jabberd-muc
    enabled: yes
  become: yes
