---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - make
    - gcc
    - ca-certificates
    - libudns-dev
    - libexpat1-dev
    - libidn11-dev
    - zlib1g-dev
    - libgsasl7-dev
    #- libhttp-parser-dev (needed for websockets only))
    - libssl-dev
    - libmysqlclient-dev
  become: yes

# init-file
- name: install init.d
  copy:
    src: jabberd.init.sh
    dest: /etc/init.d/jabberd
    mode: 'a+x'
  become: yes
